# Generated by Django 5.2.10 on 2026-05-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftJob',
            fields=[
                ('draft_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phase', models.CharField(max_length=255)),
                ('saved_filters', models.TextField()),
                ('job_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('shoot_date', models.CharField(blank=True, max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'jobs_talent_drafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_created_by_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(max_length=100)),
                ('applicants_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('selftapes_count', models.PositiveIntegerField(default=0)),
                ('ecastings_count', models.PositiveIntegerField(default=0)),
                ('polas_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'jobs_talent_job',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobAIResult',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('suggested_talents', models.TextField(blank=True, null=True)),
                ('shoot_date', models.TextField(blank=True, null=True)),
                ('requested_selftapes', models.TextField(blank=True, null=True)),
                ('requested_ecastings', models.TextField(blank=True, null=True)),
                ('requested_polas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs_ai_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_record', models.URLField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
