# Generated by Django 5.2.10 on 2026-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_record', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='meeting_record',
        ),
        migrations.AddField(
            model_name='meetings',
            name='records',
            field=models.ManyToManyField(related_name='meeting_records', to='jobs.meetingrecord'),
        ),
    ]
