# Generated by Django 5.2.10 on 2026-06-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_meetingrecord_remove_meetings_meeting_record_and_more'),
        ('talent', '0009_alter_talent_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=250)),
                ('assign_status', models.BooleanField(default=True)),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.talent')),
            ],
        ),
    ]
