# Generated by Django 5.2.10 on 2026-06-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job',
            field=models.ForeignKey(db_column='job_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
