# Generated by Django 5.2.10 on 2026-06-18 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobrole_job'),
        ('talent', '0009_alter_talent_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.talent'),
        ),
    ]
