# Generated by Django 5.2.10 on 2026-06-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobrole_job_alter_jobrole_talent'),
        ('talent', '0009_alter_talent_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job',
            field=models.ForeignKey(db_column='job_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='talent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='talent.talent'),
            preserve_default=False,
        ),
    ]
