# Generated by Django 5.2.10 on 2026-06-18 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobrole_job_alter_jobrole_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
