# Generated by Django 5.2.10 on 2026-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobrole_job_alter_meetings_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHiddenJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveIntegerField()),
                ('job_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('agent_id', 'job_id')},
            },
        ),
    ]
