# Generated by Django 5.2.10 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_agenthiddenjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolaLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('pola_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_pola_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolaRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('talent_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('responded', 'Responded')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs_pola_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfTapeLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('tape_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_selftape_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelfTapeRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('talent_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('responded', 'Responded')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs_selftape_requests',
                'managed': False,
            },
        ),
    ]
