# Generated by Django 5.2.10 on 2026-10-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_polalink_polarequest_selftapelink_selftaperequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.BigIntegerField()),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs_talent_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRoleAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jobs_jobrole_assignments',
                'managed': False,
            },
        ),
    ]
