# Generated by Django 5.2.10 on 2026-10-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_booking_jobroleassignment'),
        ('talent', '0013_team_webimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='talent.talent'),
        ),
    ]
