# Generated by Django 5.2.10 on 2026-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecastingsession',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ecastingsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
