# Generated by Django 5.2.10 on 2026-07-28 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0009_alter_talent_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_portal_guest_clients',
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('job_id', 'email'), name='uniq_guest_per_job_email')],
            },
        ),
        migrations.CreateModel(
            name='ClientChatThread',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('guest_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='client_portal.guestclient')),
            ],
            options={
                'db_table': 'client_portal_chat_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.PositiveIntegerField(db_index=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client_portal.guestclient')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_comments', to='talent.talent')),
            ],
            options={
                'db_table': 'client_portal_talent_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='client_chat_attachments/')),
                ('is_seen_by_agent', models.BooleanField(default=False)),
                ('is_seen_by_client', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_guest_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client_portal.clientchatthread')),
            ],
            options={
                'db_table': 'client_portal_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='client_port_thread__45736a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TalentFavorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='client_portal.guestclient')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_favorites', to='talent.talent')),
            ],
            options={
                'db_table': 'client_portal_talent_favorites',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('guest_client', 'talent'), name='uniq_favorite_per_guest_talent')],
            },
        ),
    ]
