# Generated by Django 5.2.10 on 2026-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestclient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestclient',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='guestclient',
            name='otp_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
