# Generated by Django 5.2.10 on 2026-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Client', 'Client')], default='Client', max_length=10),
        ),
    ]
