"""STORAGESSTORAGES
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i$_65q7!cg(n#h)!8b35_f_ydhdn(8_q938_=7#6j!pg^iqdln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'accounts.User'
# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_cleanup.apps.CleanupConfig',
    'corsheaders',
    'accounts',
    'settings',
    'talent',
    "channels",
    "chat",
    "client_portal",
    "jobs",
    "ecasting",
]


# ── Unfold Admin Theme ──────────────────────────────────────────────
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "PoolOfCast",
    "SITE_HEADER": "PoolOfCast Admin",
    "SITE_SYMBOL": "theater_comedy",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {},
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Users & Auth",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "group_work",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": "Talent Management",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Talents",
                        "icon": "star",
                        "link": reverse_lazy("admin:talent_talent_changelist"),
                    },
                    {
                        "title": "Talent Images",
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:talent_talentimage_changelist"),
                    },
                    {
                        "title": "Available Dates",
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:talent_talentavailabledate_changelist"),
                    },
                    {
                        "title": "Teams",
                        "icon": "diversity_3",
                        "link": reverse_lazy("admin:talent_team_changelist"),
                    },
                    {
                        "title": "Web Images",
                        "icon": "image",
                        "link": reverse_lazy("admin:talent_webimages_changelist"),
                    },
                ],
            },
            {
                "title": "Messaging",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Conversations",
                        "icon": "forum",
                        "link": reverse_lazy("admin:chat_conversation_changelist"),
                    },
                    {
                        "title": "Messages",
                        "icon": "chat_bubble",
                        "link": reverse_lazy("admin:chat_message_changelist"),
                    },
                ],
            },
            {
                "title": "Client Portal",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Guest Clients",
                        "icon": "person_search",
                        "link": reverse_lazy("admin:client_portal_guestclient_changelist"),
                    },
                    {
                        "title": "Client Threads",
                        "icon": "question_answer",
                        "link": reverse_lazy("admin:client_portal_clientchatthread_changelist"),
                    },
                    {
                        "title": "Client Messages",
                        "icon": "mark_chat_read",
                        "link": reverse_lazy("admin:client_portal_clientchatmessage_changelist"),
                    },
                    {
                        "title": "Comments",
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:client_portal_talentcomment_changelist"),
                    },
                    {
                        "title": "Favorites",
                        "icon": "favorite",
                        "link": reverse_lazy("admin:client_portal_talentfavorite_changelist"),
                    },
                ],
            },
            {
                "title": "E-Casting",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Sessions",
                        "icon": "videocam",
                        "link": reverse_lazy("admin:ecasting_ecastingsession_changelist"),
                    },
                    {
                        "title": "Participants",
                        "icon": "group_add",
                        "link": reverse_lazy("admin:ecasting_ecastingparticipant_changelist"),
                    },
                ],
            },
            {
                "title": "Jobs & Meetings",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Meetings",
                        "icon": "video_call",
                        "link": reverse_lazy("admin:jobs_meetings_changelist"),
                    },
                    {
                        "title": "Meeting Records",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:jobs_meetingrecord_changelist"),
                    },
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:jobs_notifications_changelist"),
                    },
                ],
            },
            {
                "title": "Site Settings",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Privacy Policy",
                        "icon": "policy",
                        "link": reverse_lazy("admin:settings_privacypolicy_changelist"),
                    },
                    {
                        "title": "Terms & Conditions",
                        "icon": "gavel",
                        "link": reverse_lazy("admin:settings_termsandcondition_changelist"),
                    },
                    {
                        "title": "About Us",
                        "icon": "info",
                        "link": reverse_lazy("admin:settings_aboutus_changelist"),
                    },
                    {
                        "title": "Contact Messages",
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:settings_contactmessage_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


import dj_database_url
DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://neondb_owner:npg_2cw1djYtoSAF@ep-dark-dream-al771qe0-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
        conn_max_age=600,
        ssl_require=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


import os
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# settings.py

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CastLinkAI API',
    'DESCRIPTION': (
        'API for CastLinkAI. Most endpoints are documented from their default '
        'DRF introspection; the Client Portal endpoints (guest chat, comments, '
        'favorites on shortlist links) carry full request/response documentation.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'TAGS': [
        {'name': 'Client Portal - Guest', 'description': 'Public shortlist-link endpoints, authenticated via the X-Guest-Token header (no login).'},
        {'name': 'Client Portal - Agent', 'description': 'Agent-facing dashboard endpoints for guest clients on a job, authenticated via JWT.'},
    ],
}


# SMTP_SETUP-----
# EMAIL_USE_SSL = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'noreplay820@gmail.com'
# EMAIL_HOST_PASSWORD = 'acjgoiavxgajkswn'
# EMAIL_PORT = 465
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "abunomanbasarjvai@gmail.com"
EMAIL_HOST_PASSWORD = "mblv sdke scmf icmn"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-guest-token",
]

CORS_ALLOWED_ORIGINS = [
    "https://api.poolofcast.com",
    "https://poolofcast.com",
    "https://www.poolofcast.com",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://69.62.116.203",
]


USE_REDIS =False

if USE_REDIS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


ZEGO_APP_ID = 3874040
ZEGO_SERVER_SECRET = "fff690a3edf1b3db2a5b56afcf6db528"
FRONTEND_URL = "https://poolofcast.com"


