import json
from datetime import date, timedelta

from django.contrib.auth import get_user_model
from django.core import mail
from django.db import connection
from django.test import TestCase, override_settings
from django.utils import timezone
from rest_framework_simplejwt.tokens import RefreshToken

from talent.models import ShortListedTalent, Talent, TalentAvailableDate
from .models import Booking, DraftJob, Job, JobAIResult, JobRole, JobRoleAssignment

User = get_user_model()

# jobs_talent_job / jobs_ai_results / jobs_talent_drafts / jobs_shortlisted_talents /
# jobs_talent_bookings / jobs_jobrole_assignments are all managed=False (FastAPI-owned)
# and have no existing Django migration that creates them, so a fresh test DB needs
# them recreated manually here, mirroring the live production schema. jobs_jobrole
# and talent_available_dates ARE Django-managed, so no manual DDL for those. Executed
# after super().setUpClass() opens TestCase's class-level transaction, so this rolls
# back automatically in tearDownClass - no leftover state.
UNMANAGED_TABLES_DDL = """
CREATE TABLE jobs_talent_job (
    job_id integer PRIMARY KEY,
    job_created_by_id bigint NOT NULL,
    session_id varchar(255),
    title varchar(255) NOT NULL,
    description text NOT NULL,
    location varchar(255) NOT NULL,
    budget_min numeric(10,2),
    budget_max numeric(10,2),
    job_type varchar(100) NOT NULL,
    applicants_count integer NOT NULL DEFAULT 0,
    shortlisted_count integer NOT NULL DEFAULT 0,
    selftapes_count integer NOT NULL DEFAULT 0,
    ecastings_count integer NOT NULL DEFAULT 0,
    polas_count integer NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL,
    currency varchar(10) NOT NULL DEFAULT '$',
    casting_roles text,
    job_photo varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE jobs_ai_results (
    result_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id integer NOT NULL REFERENCES jobs_talent_job(job_id),
    session_id integer NOT NULL,
    notes text,
    prompt_snapshot text,
    suggested_talents json,
    requested_selftapes json,
    requested_ecastings json,
    requested_polas json,
    shoot_date varchar,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE jobs_talent_drafts (
    draft_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    session_id varchar(255),
    phase varchar(255),
    saved_filters json,
    title varchar(255),
    description text,
    last_updated timestamptz NOT NULL DEFAULT now(),
    job_type varchar(100),
    location varchar(255),
    shoot_date varchar(255),
    budget varchar(255),
    casting_roles text
);

CREATE TABLE jobs_shortlisted_talents (
    shortlisted_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(255),
    talent_id bigint NOT NULL REFERENCES talents(talent_id),
    user_id bigint NOT NULL,
    job_id integer REFERENCES jobs_talent_job(job_id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE jobs_talent_bookings (
    booking_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(255),
    user_id bigint NOT NULL,
    talent_id bigint NOT NULL REFERENCES talents(talent_id),
    job_id integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    booking_date date
);

CREATE TABLE jobs_jobrole_assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id integer NOT NULL,
    job_role_id bigint NOT NULL REFERENCES jobs_jobrole(id),
    talent_id bigint NOT NULL REFERENCES talents(talent_id),
    created_at timestamptz NOT NULL DEFAULT now()
);
"""


@override_settings(EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend")
class ShortlistBookingEndpointTests(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        with connection.cursor() as cursor:
            cursor.execute(UNMANAGED_TABLES_DDL)

    def setUp(self):
        self.owner_user = User.objects.create_user(
            email="sb_owner@example.com", password="pass12345", phone="4000000001",
            full_name="Owner", role="Client", is_active=True,
        )
        self.agent_user = User.objects.create_user(
            email="sb_agent@example.com", password="pass12345", phone="4000000002",
            full_name="Agent", role="Agent", is_active=True,
        )
        self.talent = Talent.objects.create(
            role="model", character="Actor", agent=self.agent_user, gender="female",
            name="Booking Talent", skills="acting", location="Dhaka",
        )

        self.job = Job.objects.create(
            job_id="93001",
            job_created_by_id=self.owner_user.user_id,
            session_id="sb-session-1",
            title="Shortlist Test Job",
            description="desc",
            casting_roles=json.dumps([]),
            location="Dhaka",
            job_type="commercial",
            status="active",
            currency="$",
            created_at=timezone.now(),
            updated_at=timezone.now(),
        )

        self.owner_auth_header = self._auth_header(self.owner_user)

        self.available_date_1 = date.today() + timedelta(days=10)
        self.available_date_2 = date.today() + timedelta(days=11)
        TalentAvailableDate.objects.create(
            talent=self.talent, available_date=self.available_date_1, is_active=True
        )
        TalentAvailableDate.objects.create(
            talent=self.talent, available_date=self.available_date_2, is_active=True
        )

    def _auth_header(self, user):
        token = RefreshToken.for_user(user)
        return {"HTTP_AUTHORIZATION": f"Bearer {token.access_token}"}

    def _post_json(self, url, payload, auth=None):
        headers = auth if auth is not None else self.owner_auth_header
        return self.client.post(
            url, data=json.dumps(payload), content_type="application/json", **headers
        )

    # ---------- shortlist ----------

    def test_shortlist_with_job_increments_count_and_notifies(self):
        resp = self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": self.talent.talent_id}
        )
        body = resp.json()
        print("SHORTLIST(job) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(body["status_message"], f"Talent {self.talent.name} shortlisted.")

        self.job.refresh_from_db()
        self.assertEqual(self.job.shortlisted_count, 1)

        record = ShortListedTalent.objects.get(user_id=self.owner_user.user_id, talent=self.talent)
        self.assertEqual(record.job_id, self.job.job_id)

        self.assertEqual(len(mail.outbox), 1)
        self.assertEqual(mail.outbox[0].to, [self.agent_user.email])

    def test_shortlist_without_job_uses_session_and_draft_title(self):
        DraftJob.objects.create(
            draft_id="700001", user_id=self.owner_user.user_id, session_id="draft-sess-1",
            title="Draft Project", description="d", phase="p", saved_filters="{}",
            job_type="commercial", location="Dhaka", shoot_date=json.dumps(["2026-05-01"]),
            last_updated=timezone.now(),
        )
        resp = self._post_json(
            "/api/v1/talents/shortlist",
            {"talent_id": self.talent.talent_id, "session_id": "draft-sess-1"},
        )
        body = resp.json()
        print("SHORTLIST(session/draft) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)

        record = ShortListedTalent.objects.get(user_id=self.owner_user.user_id, talent=self.talent)
        self.assertIsNone(record.job)
        self.assertEqual(record.session_id, "draft-sess-1")

        notif_event = mail.outbox[0].body
        self.assertIn("Draft Project", notif_event)
        self.assertIn("2026-05-01", notif_event)

    def test_shortlist_missing_job_and_session_returns_400(self):
        resp = self._post_json("/api/v1/talents/shortlist", {"talent_id": self.talent.talent_id})
        self.assertEqual(resp.status_code, 400)

    def test_shortlist_talent_not_found(self):
        resp = self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": 999999}
        )
        self.assertEqual(resp.status_code, 404)

    def test_shortlist_duplicate_returns_400(self):
        self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": self.talent.talent_id}
        )
        resp = self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": self.talent.talent_id}
        )
        body = resp.json()
        print("SHORTLIST(dup) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("already shortlisted", body["status_message"])

    def test_shortlist_requires_auth(self):
        resp = self.client.post(
            "/api/v1/talents/shortlist",
            data=json.dumps({"job_id": self.job.job_id, "talent_id": self.talent.talent_id}),
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 401)

    # ---------- delete-shortlist ----------

    def test_delete_shortlist_by_job_id(self):
        self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": self.talent.talent_id}
        )
        resp = self.client.delete(
            f"/api/v1/talents/delete-shortlist?talent_id={self.talent.talent_id}&job_id={self.job.job_id}",
            **self.owner_auth_header,
        )
        body = resp.json()
        print("DELETE SHORTLIST(job) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)

        self.job.refresh_from_db()
        self.assertEqual(self.job.shortlisted_count, 0)
        self.assertFalse(
            ShortListedTalent.objects.filter(user_id=self.owner_user.user_id, talent=self.talent).exists()
        )

    def test_delete_shortlist_not_found(self):
        resp = self.client.delete(
            f"/api/v1/talents/delete-shortlist?talent_id={self.talent.talent_id}&job_id={self.job.job_id}",
            **self.owner_auth_header,
        )
        self.assertEqual(resp.status_code, 404)

    def test_delete_shortlist_missing_filters_returns_400(self):
        resp = self.client.delete(
            f"/api/v1/talents/delete-shortlist?talent_id={self.talent.talent_id}",
            **self.owner_auth_header,
        )
        self.assertEqual(resp.status_code, 400)

    # ---------- delete-all-shortlists ----------

    def test_delete_all_shortlists(self):
        agent2 = User.objects.create_user(
            email="sb_agent2@example.com", password="pass12345", phone="4000000003",
            full_name="Agent2", role="Agent", is_active=True,
        )
        talent2 = Talent.objects.create(
            role="model", character="Actor", agent=agent2, gender="male",
            name="Talent2", skills="acting", location="Dhaka",
        )
        self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": self.talent.talent_id}
        )
        self._post_json(
            "/api/v1/talents/shortlist", {"job_id": self.job.job_id, "talent_id": talent2.talent_id}
        )

        resp = self.client.delete(
            f"/api/v1/jobs/delete-all-shortlists?job_id={self.job.job_id}", **self.owner_auth_header
        )
        body = resp.json()
        print("DELETE ALL SHORTLISTS ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("Successfully removed 2", body["status_message"])

        self.job.refresh_from_db()
        self.assertEqual(self.job.shortlisted_count, 0)
        self.assertEqual(ShortListedTalent.objects.filter(job=self.job).count(), 0)

    def test_delete_all_shortlists_none_to_remove(self):
        resp = self.client.delete(
            f"/api/v1/jobs/delete-all-shortlists?job_id={self.job.job_id}", **self.owner_auth_header
        )
        body = resp.json()
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(body["status_message"], "No shortlisted talents to remove for this job.")

    def test_delete_all_shortlists_unauthorized_job_404(self):
        resp = self.client.delete(
            "/api/v1/jobs/delete-all-shortlists?job_id=999999", **self.owner_auth_header
        )
        self.assertEqual(resp.status_code, 404)

    # ---------- book ----------

    def test_book_success_creates_bookings_and_autoshortlists(self):
        resp = self._post_json(
            "/api/v1/talents/book",
            {
                "job_id": self.job.job_id,
                "talent_id": self.talent.talent_id,
                "booking_dates": [self.available_date_1.isoformat(), self.available_date_2.isoformat()],
            },
        )
        body = resp.json()
        print("BOOK ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("booked successfully", body["status_message"])

        self.assertEqual(
            Booking.objects.filter(user_id=self.owner_user.user_id, talent=self.talent).count(), 2
        )
        self.job.refresh_from_db()
        self.assertEqual(self.job.shortlisted_count, 1)
        self.assertTrue(
            ShortListedTalent.objects.filter(user_id=self.owner_user.user_id, talent=self.talent, job=self.job).exists()
        )

        self.assertFalse(
            TalentAvailableDate.objects.filter(
                talent=self.talent, available_date=self.available_date_1, is_active=True
            ).exists()
        )

        self.assertEqual(len(mail.outbox), 1)

    def test_book_includes_role_text_when_assigned(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent)
        JobRoleAssignment.objects.create(job_id=int(self.job.job_id), job_role=role, talent=self.talent)

        resp = self._post_json(
            "/api/v1/talents/book",
            {
                "job_id": self.job.job_id,
                "talent_id": self.talent.talent_id,
                "booking_dates": [self.available_date_1.isoformat()],
            },
        )
        body = resp.json()
        print("BOOK(with role) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("as Lead", body["status_message"])
        self.assertIn("(Lead)", mail.outbox[0].subject)

    def test_book_no_dates_returns_400(self):
        resp = self._post_json(
            "/api/v1/talents/book",
            {"job_id": self.job.job_id, "talent_id": self.talent.talent_id, "booking_dates": []},
        )
        self.assertEqual(resp.status_code, 400)

    def test_book_unavailable_date_returns_400(self):
        unavailable = date.today() + timedelta(days=99)
        resp = self._post_json(
            "/api/v1/talents/book",
            {
                "job_id": self.job.job_id,
                "talent_id": self.talent.talent_id,
                "booking_dates": [unavailable.isoformat()],
            },
        )
        body = resp.json()
        print("BOOK(unavailable) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("not available", body["status_message"])

    def test_book_conflicting_date_returns_400(self):
        self._post_json(
            "/api/v1/talents/book",
            {
                "job_id": self.job.job_id,
                "talent_id": self.talent.talent_id,
                "booking_dates": [self.available_date_1.isoformat()],
            },
        )
        TalentAvailableDate.objects.filter(
            talent=self.talent, available_date=self.available_date_1
        ).update(is_active=True)
        resp = self._post_json(
            "/api/v1/talents/book",
            {
                "job_id": self.job.job_id,
                "talent_id": self.talent.talent_id,
                "booking_dates": [self.available_date_1.isoformat()],
            },
        )
        body = resp.json()
        print("BOOK(conflict) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("already booked", body["status_message"])

    def test_book_requires_auth(self):
        resp = self.client.post(
            "/api/v1/talents/book",
            data=json.dumps(
                {
                    "job_id": self.job.job_id,
                    "talent_id": self.talent.talent_id,
                    "booking_dates": [self.available_date_1.isoformat()],
                }
            ),
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 401)
