import json

from django.contrib.auth import get_user_model
from django.db import connection
from django.test import TestCase
from django.utils import timezone
from rest_framework_simplejwt.tokens import RefreshToken

from talent.models import Talent
from .models import Job, JobRole, JobRoleAssignment

User = get_user_model()

# jobs_talent_job / jobs_jobrole_assignments are managed=False (FastAPI-owned) and have
# no existing Django migration that creates them, so a fresh test DB needs them recreated
# manually here, mirroring the live production schema. jobs_jobrole itself IS Django-
# managed (migration 0004, with talent_id made nullable in migration 0012), so no manual
# DDL is needed for it. Executed after super().setUpClass() opens TestCase's class-level
# transaction, so this rolls back automatically in tearDownClass - no leftover state.
UNMANAGED_TABLES_DDL = """
CREATE TABLE jobs_talent_job (
    job_id integer PRIMARY KEY,
    job_created_by_id bigint NOT NULL,
    session_id varchar(255),
    title varchar(255) NOT NULL,
    description text NOT NULL,
    location varchar(255) NOT NULL,
    budget_min numeric(10,2),
    budget_max numeric(10,2),
    job_type varchar(100) NOT NULL,
    applicants_count integer NOT NULL DEFAULT 0,
    shortlisted_count integer NOT NULL DEFAULT 0,
    selftapes_count integer NOT NULL DEFAULT 0,
    ecastings_count integer NOT NULL DEFAULT 0,
    polas_count integer NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL,
    currency varchar(10) NOT NULL DEFAULT '$',
    casting_roles text,
    job_photo varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE jobs_jobrole_assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id integer NOT NULL,
    job_role_id bigint NOT NULL REFERENCES jobs_jobrole(id),
    talent_id bigint NOT NULL REFERENCES talents(talent_id),
    created_at timestamptz NOT NULL DEFAULT now()
);
"""


class RoleAssignmentEndpointTests(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        with connection.cursor() as cursor:
            cursor.execute(UNMANAGED_TABLES_DDL)

    def setUp(self):
        self.owner_user = self._make_user("owner@example.com", "3000000000", role="Client")
        self.other_user = self._make_user("other@example.com", "3000000003", role="Client")
        self.agent_user_a = self._make_user("agent_a@example.com", "3000000001")
        self.agent_user_b = self._make_user("agent_b@example.com", "3000000002")

        self.talent_a = Talent.objects.create(
            role="model", character="Actor", agent=self.agent_user_a, gender="female",
            name="Talent A", skills="acting", location="Dhaka",
        )
        self.talent_b = Talent.objects.create(
            role="model", character="Actor", agent=self.agent_user_b, gender="male",
            name="Talent B", skills="acting", location="Dhaka",
        )

        self.job = Job.objects.create(
            job_id="92001",
            job_created_by_id=self.owner_user.user_id,
            session_id="role-session-1",
            title="Role Test Job",
            description="desc",
            casting_roles=json.dumps(["Lead", "Supporting"]),
            location="Dhaka",
            job_type="commercial",
            status="active",
            currency="$",
            created_at=timezone.now(),
            updated_at=timezone.now(),
        )

        self.owner_auth_header = self._auth_header(self.owner_user)
        self.other_auth_header = self._auth_header(self.other_user)

    def _make_user(self, email, phone, role="Agent"):
        return User.objects.create_user(
            email=email, password="pass12345", phone=phone, full_name=email,
            role=role, is_active=True,
        )

    def _auth_header(self, user):
        token = RefreshToken.for_user(user)
        return {"HTTP_AUTHORIZATION": f"Bearer {token.access_token}"}

    # ---------- available-roles ----------

    def test_available_roles_requires_job_id_or_session_id(self):
        resp = self.client.get("/api/v1/jobs/available-roles")
        self.assertEqual(resp.status_code, 400)

    def test_available_roles_unknown_session_returns_empty_list(self):
        resp = self.client.get("/api/v1/jobs/available-roles?session_id=does-not-exist")
        print("AVAILABLE ROLES (unknown session) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json(), [])

    def test_available_roles_canonicalizes_duplicate_role_names(self):
        role1 = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        role2 = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_b)
        JobRole.objects.create(job=self.job, job_role="Supporting", talent=None)

        resp = self.client.get(f"/api/v1/jobs/available-roles?job_id={self.job.job_id}")
        body = resp.json()
        print("AVAILABLE ROLES (canonicalize) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(body), 2)

        lead_entry = next(r for r in body if r["job_role"] == "Lead")
        self.assertEqual(lead_entry["id"], role1.id)
        self.assertEqual(sorted(lead_entry["talent_id"]), sorted([self.talent_a.talent_id, self.talent_b.talent_id]))
        self.assertTrue(lead_entry["assign_status"])
        self.assertIsNone(lead_entry["session_id"])

        supporting_entry = next(r for r in body if r["job_role"] == "Supporting")
        self.assertEqual(supporting_entry["talent_id"], [])
        self.assertFalse(supporting_entry["assign_status"])

    def test_available_roles_by_session_id_uses_latest_job(self):
        resp = self.client.get(f"/api/v1/jobs/available-roles?session_id={self.job.session_id}")
        self.assertEqual(resp.status_code, 200)

    # ---------- assign-role ----------

    def test_assign_role_creates_new_row_and_assignment(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)

        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
            **self.owner_auth_header,
        )
        body = resp.json()
        print("ASSIGN ROLE ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("successfully assigned", body["status_message"])

        source_role.refresh_from_db()
        self.assertIsNone(source_role.talent_id)  # original row untouched

        new_rows = JobRole.objects.filter(job=self.job, job_role="Lead", talent_id=self.talent_a.talent_id)
        self.assertEqual(new_rows.count(), 1)
        new_role = new_rows.first()
        self.assertTrue(
            JobRoleAssignment.objects.filter(job_role_id=new_role.id, talent_id=self.talent_a.talent_id).exists()
        )

    def test_assign_role_already_assigned_on_source_row_is_noop(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)

        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
            **self.owner_auth_header,
        )
        body = resp.json()
        print("ASSIGN ROLE (already on source) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("already assigned", body["status_message"])
        self.assertEqual(JobRole.objects.filter(job=self.job, job_role="Lead").count(), 1)

    def test_assign_role_already_assigned_on_other_row_is_noop(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)

        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
            **self.owner_auth_header,
        )
        body = resp.json()
        print("ASSIGN ROLE (already on other row) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)
        self.assertIn("already assigned", body["status_message"])
        self.assertEqual(JobRole.objects.filter(job=self.job, job_role="Lead").count(), 2)

    def test_assign_role_not_found(self):
        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": 999999, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
            **self.owner_auth_header,
        )
        self.assertEqual(resp.status_code, 404)

    def test_assign_role_talent_not_found(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": 999999}),
            content_type="application/json",
            **self.owner_auth_header,
        )
        self.assertEqual(resp.status_code, 404)

    def test_assign_role_requires_auth(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 401)

    def test_assign_role_rejects_non_owner(self):
        source_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        resp = self.client.post(
            "/api/v1/jobs/assign-role",
            data=json.dumps({"id": source_role.id, "talent_id": self.talent_a.talent_id}),
            content_type="application/json",
            **self.other_auth_header,
        )
        print("ASSIGN ROLE (non-owner) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 403)

    # ---------- unassign-role ----------

    def test_unassign_role_missing_params_returns_400(self):
        resp = self.client.patch("/api/v1/jobs/unassign-role", **self.owner_auth_header)
        self.assertEqual(resp.status_code, 400)

    def test_unassign_role_requires_auth(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        resp = self.client.patch(f"/api/v1/jobs/unassign-role?job_role_id={role.id}")
        self.assertEqual(resp.status_code, 401)

    def test_unassign_role_rejects_non_owner(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_role_id={role.id}", **self.other_auth_header
        )
        print("UNASSIGN (non-owner) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 403)

    def test_unassign_role_by_job_role_id_clears_canonical_row(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        JobRoleAssignment.objects.create(job_id=int(self.job.job_id), job_role=role, talent=self.talent_a)

        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_role_id={role.id}", **self.owner_auth_header
        )
        body = resp.json()
        print("UNASSIGN (by role id) ->", resp.status_code, body)
        self.assertEqual(resp.status_code, 200)

        role.refresh_from_db()
        self.assertIsNone(role.talent_id)
        self.assertFalse(role.assign_status)
        self.assertFalse(JobRoleAssignment.objects.filter(job_role_id=role.id).exists())

    def test_unassign_role_falls_back_to_remaining_assignment(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        JobRoleAssignment.objects.create(job_id=int(self.job.job_id), job_role=role, talent=self.talent_a)
        JobRoleAssignment.objects.create(job_id=int(self.job.job_id), job_role=role, talent=self.talent_b)

        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_role_id={role.id}", **self.owner_auth_header
        )
        print("UNASSIGN (fallback remaining) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 200)

        role.refresh_from_db()
        self.assertEqual(role.talent_id, self.talent_b.talent_id)
        self.assertTrue(role.assign_status)

    def test_unassign_role_by_job_id_single_assigned_role(self):
        role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        JobRole.objects.create(job=self.job, job_role="Supporting", talent=None)
        JobRoleAssignment.objects.create(job_id=int(self.job.job_id), job_role=role, talent=self.talent_a)

        resp = self.client.delete(
            f"/api/v1/jobs/unassign-role?job_id={self.job.job_id}", **self.owner_auth_header
        )
        print("UNASSIGN (by job_id, delete method) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 200)

        role.refresh_from_db()
        self.assertIsNone(role.talent_id)

    def test_unassign_role_by_job_id_multiple_assigned_roles_returns_400(self):
        role1 = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        role2 = JobRole.objects.create(job=self.job, job_role="Supporting", talent=self.talent_b)

        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_id={self.job.job_id}", **self.owner_auth_header
        )
        self.assertEqual(resp.status_code, 400)

    def test_unassign_role_by_job_id_no_assigned_roles_returns_404(self):
        JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_id={self.job.job_id}", **self.owner_auth_header
        )
        self.assertEqual(resp.status_code, 404)

    def test_unassign_role_null_target_falls_back_to_sibling_row(self):
        empty_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=None)
        assigned_role = JobRole.objects.create(job=self.job, job_role="Lead", talent=self.talent_a)
        JobRoleAssignment.objects.create(
            job_id=int(self.job.job_id), job_role=empty_role, talent=self.talent_a
        )

        resp = self.client.patch(
            f"/api/v1/jobs/unassign-role?job_role_id={empty_role.id}", **self.owner_auth_header
        )
        print("UNASSIGN (null target, sibling fallback) ->", resp.status_code, resp.json())
        self.assertEqual(resp.status_code, 200)

        empty_role.refresh_from_db()
        self.assertIsNone(empty_role.talent_id)  # untouched - spec only updates target_role when it held the talent
        self.assertFalse(
            JobRoleAssignment.objects.filter(job_role_id=empty_role.id, talent_id=self.talent_a.talent_id).exists()
        )
