# Generated by Django 5.2.10 on 2026-04-03 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('talent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('model', 'Model'), ('actor', 'Actor')], default='model', max_length=20)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Nonbinary')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('waist', models.CharField(blank=True, max_length=50, null=True)),
                ('bust', models.CharField(blank=True, max_length=50, null=True)),
                ('hips', models.CharField(blank=True, max_length=50, null=True)),
                ('dress_size', models.CharField(blank=True, max_length=50, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_colour', models.CharField(blank=True, max_length=100, null=True)),
                ('eye_colour', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_type', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_talents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'talents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentBookingDate',
            fields=[
                ('booking_date_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booked_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_talents', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_dates', to='talent.talent')),
            ],
            options={
                'db_table': 'talent_booking_dates',
                'ordering': ['booked_date'],
            },
        ),
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='talents/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='talent.talent')),
            ],
            options={
                'db_table': 'talent_images',
                'ordering': ['image_id'],
            },
        ),
        migrations.CreateModel(
            name='TalentAvailableDate',
            fields=[
                ('availability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='talent.talent')),
            ],
            options={
                'db_table': 'talent_available_dates',
                'ordering': ['available_date'],
                'constraints': [models.UniqueConstraint(fields=('talent', 'available_date'), name='unique_talent_available_date')],
            },
        ),
    ]
