# Generated by Django 5.2.10 on 2026-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListedTalent',
            fields=[
                ('shortlisted_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'jobs_shortlisted_talents',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
