# Generated by Django 5.2.10 on 2026-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_shortlistedtalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='is_available_on_request',
            field=models.BooleanField(default=True),
        ),
    ]
