# Generated by Django 5.2.10 on 2026-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_talent_is_available_talent_is_available_on_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='character',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
