# Generated by Django 5.2.10 on 2026-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_talent_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='character',
            field=models.CharField(choices=[('lead_male', 'Lead Male'), ('lead_female', 'Lead Female'), ('extra', 'Extra')], default='extra', max_length=20),
        ),
    ]
