# Generated by Django 5.2.10 on 2026-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_alter_talent_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='skills',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
