# Generated by Django 5.2.10 on 2026-05-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_talent_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='character',
            field=models.CharField(choices=[('actor', 'Actor'), ('model', 'Model'), ('character', 'Character'), ('influencer', 'Influencer'), ('performer', 'Performer'), ('dancer', 'Dancer'), ('kid', 'Kid'), ('plus_size', 'Plus Size')], default='actor', max_length=20),
        ),
    ]
