# Generated by Django 5.2.10 on 2026-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_alter_talent_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='character',
            field=models.CharField(choices=[('Actor', 'Actor'), ('model', 'Model'), ('Model', 'Character'), ('Influencer', 'Influencer'), ('Performer', 'Performer'), ('Dancer', 'Dancer'), ('Kid', 'Kid'), ('Plus Size', 'Plus Size')], default='actor', max_length=20),
        ),
    ]
