# Generated by Django 5.2.10 on 2026-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_alter_talent_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
