# Generated by Django 5.2.10 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_talent_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
