# Generated by Django 5.2.10 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0011_talent_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
