# Generated by Django 5.2.10 on 2026-09-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0012_talent_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='team_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge1', models.ImageField(upload_to='webimage')),
                ('iamge2', models.ImageField(upload_to='webimage')),
                ('iamge3', models.ImageField(upload_to='webimage')),
                ('iamge4', models.ImageField(upload_to='webimage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
