# Generated by Django 5.2.10 on 2026-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0013_team_webimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_id', models.BigIntegerField(unique=True)),
                ('job_id', models.IntegerField(db_index=True)),
                ('position', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'talent_shortlist_order',
            },
        ),
    ]
